// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backendproject.Context;

namespace backendproject.Migrations
{
    [DbContext(typeof(BurgerContext))]
    [Migration("20200121130914_cors")]
    partial class cors
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0");

            modelBuilder.Entity("backendproject.Models.Bong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BongDetailsId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("created")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BongDetailsId");

                    b.ToTable("Bongs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            created = new DateTime(2020, 1, 21, 14, 9, 14, 164, DateTimeKind.Local).AddTicks(8170)
                        });
                });

            modelBuilder.Entity("backendproject.Models.BongDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IngridientId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IngridientId");

                    b.HasIndex("ProductId");

                    b.ToTable("BongsDetails");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IngridientId = 1,
                            ProductId = 1
                        },
                        new
                        {
                            Id = 2,
                            IngridientId = 1,
                            ProductId = 1
                        });
                });

            modelBuilder.Entity("backendproject.Models.Ingridient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("IngridientName")
                        .HasColumnType("TEXT");

                    b.Property<int>("Price")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Ingridients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IngridientName = "Salad",
                            Price = 1
                        },
                        new
                        {
                            Id = 2,
                            IngridientName = "Cheese",
                            Price = 2
                        },
                        new
                        {
                            Id = 3,
                            IngridientName = "Bacon",
                            Price = 3
                        },
                        new
                        {
                            Id = 4,
                            IngridientName = "Meat",
                            Price = 10
                        });
                });

            modelBuilder.Entity("backendproject.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Burger")
                        .HasColumnType("TEXT");

                    b.Property<int>("Price")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Burger = "Burger",
                            Price = 50
                        });
                });

            modelBuilder.Entity("backendproject.Models.Bong", b =>
                {
                    b.HasOne("backendproject.Models.BongDetails", "BongDetails")
                        .WithMany()
                        .HasForeignKey("BongDetailsId");
                });

            modelBuilder.Entity("backendproject.Models.BongDetails", b =>
                {
                    b.HasOne("backendproject.Models.Ingridient", "Ingridient")
                        .WithMany()
                        .HasForeignKey("IngridientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backendproject.Models.Product", "Product")
                        .WithMany("bongsDetails")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
